- hosts: "{{ variable_hosts | default('k8s-all') }}"
  become: yes
  tasks:
   - name: disable swap, if any
     become: true
     shell: swapoff -a

   - name: install APT Transport HTTPS
     apt:
       name: "{{item}}"
       state: present
     loop:
       - apt-transport-https
       - curl

   - name: add Kubernetes apt-key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubernetes-cni
     apt:
       name: kubernetes-cni=0.8.7-00
       state: present
       update_cache: true

   - name: install kubelet
     apt:
       name: kubelet=1.23.3-00
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm=1.23.3-00
       state: present

   - name: pull kube images
     become: true
     shell: kubeadm config images pull


- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl=1.23.3-00
       state: present
       force: yes
